export const russianKeyboardButtons = [
  // Ряд 1
  [
    { key: "ё", code: "Backquote", type: "symbol" },
    { key: "1", code: "Digit1", type: "symbol", shift: "!" },
    { key: "2", code: "Digit2", type: "symbol", shift: '"' },
    { key: "3", code: "Digit3", type: "symbol", shift: "№" },
    { key: "4", code: "Digit4", type: "symbol", shift: ";" },
    { key: "5", code: "Digit5", type: "symbol", shift: "%" },
    { key: "6", code: "Digit6", type: "symbol", shift: ":" },
    { key: "7", code: "Digit7", type: "symbol", shift: "?" },
    { key: "8", code: "Digit8", type: "symbol", shift: "*" },
    { key: "9", code: "Digit9", type: "symbol", shift: "(" },
    { key: "0", code: "Digit0", type: "symbol", shift: ")" },
    { key: "-", code: "Minus", type: "symbol", shift: "_" },
    { key: "=", code: "Equal", type: "symbol", shift: "+" },
    { key: "Backspace", code: "Backspace", type: "button" },
  ],

  // Ряд 2
  [
    { key: "Tab", code: "Tab", type: "button" },
    { key: "й", code: "KeyQ", type: "symbol" },
    { key: "ц", code: "KeyW", type: "symbol" },
    { key: "у", code: "KeyE", type: "symbol" },
    { key: "к", code: "KeyR", type: "symbol" },
    { key: "е", code: "KeyT", type: "symbol" },
    { key: "н", code: "KeyY", type: "symbol" },
    { key: "г", code: "KeyU", type: "symbol" },
    { key: "ш", code: "KeyI", type: "symbol" },
    { key: "щ", code: "KeyO", type: "symbol" },
    { key: "з", code: "KeyP", type: "symbol" },
    { key: "х", code: "BracketLeft", type: "symbol" },
    { key: "ъ", code: "BracketRight", type: "symbol" },
  ],

  // Ряд 3
  [
    { key: "CapsLock", code: "CapsLock", type: "button" },
    { key: "ф", code: "KeyA", type: "symbol" },
    { key: "ы", code: "KeyS", type: "symbol" },
    { key: "в", code: "KeyD", type: "symbol" },
    { key: "а", code: "KeyF", type: "symbol" },
    { key: "п", code: "KeyG", type: "symbol" },
    { key: "р", code: "KeyH", type: "symbol" },
    { key: "о", code: "KeyJ", type: "symbol" },
    { key: "л", code: "KeyK", type: "symbol" },
    { key: "д", code: "KeyL", type: "symbol" },
    { key: "ж", code: "Semicolon", type: "symbol" },
    { key: "э", code: "Quote", type: "symbol" },
    { key: "\\", code: "Backslash", type: "symbol", shift: "/" },
    { key: "Enter", code: "Enter", type: "button" },
  ],

  // Ряд 4
  [
    { key: "Shift", code: "ShiftLeft", type: "button" },
    { key: "я", code: "KeyZ", type: "symbol" },
    { key: "ч", code: "KeyX", type: "symbol" },
    { key: "с", code: "KeyC", type: "symbol" },
    { key: "м", code: "KeyV", type: "symbol" },
    { key: "и", code: "KeyB", type: "symbol" },
    { key: "т", code: "KeyN", type: "symbol" },
    { key: "ь", code: "KeyM", type: "symbol" },
    { key: "б", code: "Comma", type: "symbol" },
    { key: "ю", code: "Period", type: "symbol" },
    { key: "/", code: "Slash", type: "symbol", shift: "," },
    { key: "▲", code: "ArrowUp", type: "button" },
    { key: "Shift", code: "ShiftRight", type: "button" },
  ],

  // Ряд 5
  [
    { key: "Ctrl", code: "ControlLeft", type: "button" },
    { key: "Win", code: "MetaLeft", type: "button" },
    { key: "Alt", code: "AltLeft", type: "button" },
    { key: " ", code: "Space", type: "button" },
    { key: "Alt", code: "AltRight", type: "button" },
    { key: "Ctrl", code: "ControlRight", type: "button" },
    { key: "◄", code: "ArrowLeft", type: "button" },
    { key: "▼", code: "ArrowDown", type: "button" },
    { key: "►", code: "ArrowRight", type: "button" },
  ],
];

export const englishKeyboardButtons = [
  [
    { key: "`", code: "Backquote", type: "symbol", shift: "~" },
    { key: "1", code: "Digit1", type: "symbol", shift: "!" },
    { key: "2", code: "Digit2", type: "symbol", shift: "@" },
    { key: "3", code: "Digit3", type: "symbol", shift: "#" },
    { key: "4", code: "Digit4", type: "symbol", shift: "$" },
    { key: "5", code: "Digit5", type: "symbol", shift: "%" },
    { key: "6", code: "Digit6", type: "symbol", shift: "^" },
    { key: "7", code: "Digit7", type: "symbol", shift: "&" },
    { key: "8", code: "Digit8", type: "symbol", shift: "*" },
    { key: "9", code: "Digit9", type: "symbol", shift: "(" },
    { key: "0", code: "Digit0", type: "symbol", shift: ")" },
    { key: "-", code: "Minus", type: "symbol", shift: "_" },
    { key: "=", code: "Equal", type: "symbol", shift: "+" },
    { key: "Backspace", code: "Backspace", type: "button" },
  ],

  // Ряд 2
  [
    { key: "Tab", code: "Tab", type: "button" },
    { key: "q", code: "KeyQ", type: "symbol" },
    { key: "w", code: "KeyW", type: "symbol" },
    { key: "e", code: "KeyE", type: "symbol" },
    { key: "r", code: "KeyR", type: "symbol" },
    { key: "t", code: "KeyT", type: "symbol" },
    { key: "y", code: "KeyY", type: "symbol" },
    { key: "u", code: "KeyU", type: "symbol" },
    { key: "i", code: "KeyI", type: "symbol" },
    { key: "o", code: "KeyO", type: "symbol" },
    { key: "p", code: "KeyP", type: "symbol" },
    { key: "[", code: "BracketLeft", type: "symbol", shift: "{" },
    { key: "]", code: "BracketRight", type: "symbol", shift: "}" },
  ],

  // Ряд 3
  [
    { key: "CapsLock", code: "CapsLock", type: "button" },
    { key: "a", code: "KeyA", type: "symbol" },
    { key: "s", code: "KeyS", type: "symbol" },
    { key: "d", code: "KeyD", type: "symbol" },
    { key: "f", code: "KeyF", type: "symbol" },
    { key: "g", code: "KeyG", type: "symbol" },
    { key: "h", code: "KeyH", type: "symbol" },
    { key: "j", code: "KeyJ", type: "symbol" },
    { key: "k", code: "KeyK", type: "symbol" },
    { key: "l", code: "KeyL", type: "symbol" },
    { key: ";", code: "Semicolon", type: "symbol", shift: ":" },
    { key: "'", code: "Quote", type: "symbol", shift: '"' },
    { key: "\\", code: "Backslash", type: "symbol", shift: "|" },
    { key: "Enter", code: "Enter", type: "button" },
  ],

  // Ряд 4
  [
    { key: "Shift", code: "ShiftLeft", type: "button" },
    { key: "z", code: "KeyZ", type: "symbol" },
    { key: "x", code: "KeyX", type: "symbol" },
    { key: "c", code: "KeyC", type: "symbol" },
    { key: "v", code: "KeyV", type: "symbol" },
    { key: "b", code: "KeyB", type: "symbol" },
    { key: "n", code: "KeyN", type: "symbol" },
    { key: "m", code: "KeyM", type: "symbol" },
    { key: ",", code: "Comma", type: "symbol", shift: "<" },
    { key: ".", code: "Period", type: "symbol", shift: ">" },
    { key: "/", code: "Slash", type: "symbol", shift: "?" },
    { key: "▲", code: "ArrowUp", type: "button" },
    { key: "Shift", code: "ShiftRight", type: "button" },
  ],

  // Ряд 5
  [
    { key: "Ctrl", code: "ControlLeft", type: "button" },
    { key: "Win", code: "MetaLeft", type: "button" },
    { key: "Alt", code: "AltLeft", type: "button" },
    { key: " ", code: "Space", type: "button" },
    { key: "Alt", code: "AltRight", type: "button" },
    { key: "Ctrl", code: "ControlRight", type: "button" },
    { key: "◄", code: "ArrowLeft", type: "button" },
    { key: "▼", code: "ArrowDown", type: "button" },
    { key: "►", code: "ArrowRight", type: "button" },
  ],
];
